version: '3'
services:

  app:
    container_name: app-server
    image: nextcloud:fpm
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
    depends_on:
      - letsencrypt
      - nginx
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: mariadb:10.4.10
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-p@ssw0rd
      - MYSQL_PASSWORD=nextcloud-p@ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
      
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    restart: always
      
  nginx:
    container_name: nginx
    image: nginx
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
      - /data/nextcloud/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /data/nextcloud/nginx/html:/usr/share/nginx/html:rw
      - /data/nextcloud/nginx/certs:/etc/nginx/certs:ro
    restart: always
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    container_name: letsencrypt
    depends_on:
      - nginx
    volumes:
      - /data/nextcloud/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /data/nextcloud/nginx/html:/usr/share/nginx/html:rw
      - /data/nextcloud/nginx/certs:/etc/nginx/certs:rw
    restart: always
    
      
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
